# Generated by Django 4.2.5 on 2023-09-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_washroom_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washroom',
            name='unique_id',
            field=models.IntegerField(unique=True),
        ),
    ]
